### ISSUE TITLE
Redesign and implement new templates using the new branding

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods-appledoc#1]

**Comment by orta** [comment]
Main concerns:
- Small libraries are not well treated by the Apple style documention - Something better is @robb's http://underscorem.org
- Changes were hard to maintain in the old style due to lack of DRY. Templates should be written in a higher language and statically generated for people to use.

**Comment by kylef** [comment]
@orta Will the standalone command use the same template as cocoadocs.org?

**Comment by orta** [comment]
Could do, ATM requires scss, erb and the doc tool from Delisa
